### ISSUE TITLE
Wrong version of Dart SDK being selected

### ISSUE THREAD

**Issue by AylanBoscarino** [steebchen/flutter#5]
Trying the example yaml on this repo's readme ends up failing the install dependencies steps with the following message:

> Because exame depends on json_serializable 3.2.5 which requires SDK version >=2.6.0 <3.0.0, version solving failed.
> pub get failed (1)

My pubspect.yml file points to sdk ">=2.3.0 <3.0.0" and when running the pub get on the action it sets the version to 2.5.0

Everything runs normal on a local machine.

My action file:

```
name: Dart CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      uses: steebchen/flutter@v1.0.0
      with:
        args: pub get

    - name: run tests
      uses: steebchen/flutter@v1.0.0
      with:
        args: test

    - name: build apk
      uses: steebchen/flutter@v1.0.0
      with:
        args: build apk --release
```

The complete error message: 

![image](https://user-images.githubusercontent.com/30734219/77225742-ae0f1080-6b50-11ea-912f-ce9c624b1097.png)

Am I doing something wrong?
